### ISSUE TITLE
Minimum Java version required

### ISSUE THREAD

**Issue by sydneyhenrard** [logzio/micrometer-registry-logzio#2]
I tried to integrate the library in a Spring Boot 2 project compiled in Java 11 but it seems the library has been compiled with Java 15
```
java: cannot access io.micrometer.logzio.LogzioConfig
  bad class file: /C:/Users/sydney/.m2/repository/io/logz/micrometer/micrometer-registry-logzio/1.0/micrometer-registry-logzio-1.0.jar!/io/micrometer/logzio/LogzioConfig.class
    class file has wrong version 59.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```
Is it a correct assumption?

**Comment by yotamloe** [comment]
Hey @sydneyhenrard you are correct the library is compiled in Java 13.
We are currently working on a new release that will be compatible also with Java 11, will keep you updated shortly about that.

**Comment by yotamloe** [comment]
@sydneyhenrard We released a new version that is compatible with java 11
When you define your dependencies use:
`io.logz.micrometer:micrometer-registry-logzio:1.0.1`
Instead of:
`io.logz.micrometer:micrometer-registry-logzio:1.0`
Let me know if it solved your issue.

**Comment by sydneyhenrard** [comment]
The project is now compiling. Thanks
